site_name: " "
theme:
  name: material
  language: pt
  features:
    - navigation.instant
  palette:
    primary: green
    accent: green

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Documento de Visão: documento-de-visao.md
  - Documento de Comunição: documento-de-comunicacao.md
  - Documentos de Sprints:
      - Sprint 0: sprints/sprint0.md
      - Sprint 1: sprints/sprint1.md
      - Sprint 2: sprints/sprint2.md
  - Backlog: backlog.md
