site_name: " "
theme:
  name: material
  language: pt
  features:
    - navigation.instant
  palette:
    primary: green
    accent: green

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Teste2: documento-de-comunicacao.md
